/**
 * Downloads the brand webfonts from Google Fonts and self-hosts them.
 *
 * Self-hosted on purpose: the app must render correctly offline and inside the
 * headless Chromium that prints invoice PDFs, neither of which can rely on a CDN.
 * Re-run after changing the family list: npm run fonts
 */
import { createHash } from "node:crypto";
import { mkdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";

// Modern UA so Google serves woff2 rather than legacy formats.
const UA =
  "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36";

const FAMILIES = [
  "Montserrat:ital,wght@0,400;0,500;0,600;0,700;0,800;0,900;1,700;1,800",
  "Inter:wght@400;500;600;700",
  "JetBrains+Mono:wght@400;500",
  "Cairo:wght@600;700;800;900",
  "Tajawal:wght@400;500;700",
  /*
    Signature faces, for the "type my name instead" option. A typed signature has
    to read as a signature, and the Latin script fonts everyone reaches for have
    no Arabic coverage at all — so there are two, one per script, and the pad
    picks by what was actually typed. Aref Ruqaa is a Ruqʿah-style calligraphic
    Arabic face; Dancing Script covers Latin.
  */
  "Dancing+Script:wght@600;700",
  "Aref+Ruqaa:wght@400;700",
];

const OUT_DIR = join(process.cwd(), "public", "fonts");

async function main() {
  mkdirSync(OUT_DIR, { recursive: true });

  const url =
    "https://fonts.googleapis.com/css2?" +
    FAMILIES.map((f) => `family=${f}`).join("&") +
    "&display=swap";

  const css = await fetch(url, { headers: { "User-Agent": UA } }).then((r) => {
    if (!r.ok) throw new Error(`Google Fonts returned ${r.status}`);
    return r.text();
  });

  const urls = [...new Set([...css.matchAll(/url\((https:\/\/[^)]+\.woff2)\)/g)].map((m) => m[1]))];
  console.log(`[fonts] ${urls.length} font files to fetch`);

  const map = new Map<string, string>();
  let done = 0;
  await Promise.all(
    urls.map(async (u) => {
      const ab = (await fetch(u).then((r) => r.arrayBuffer())) as ArrayBuffer;
      const buf = Buffer.from(new Uint8Array(ab));
      const name = `f-${createHash("sha1").update(u).digest("hex").slice(0, 8)}.woff2`;
      writeFileSync(join(OUT_DIR, name), buf);
      map.set(u, `/fonts/${name}`);
      if (++done % 20 === 0) console.log(`[fonts]   ${done}/${urls.length}`);
    })
  );

  let local = css;
  for (const [remote, localPath] of map) local = local.replaceAll(remote, localPath);

  writeFileSync(
    join(OUT_DIR, "fonts.local.css"),
    `/* Generated by scripts/fetch-fonts.ts — do not edit by hand. */\n${local}`
  );

  const families = [...new Set([...local.matchAll(/font-family: '([^']+)'/g)].map((m) => m[1]))];
  console.log(`[fonts] wrote ${urls.length} files · families: ${families.join(", ")}`);
}

main().catch((e) => {
  console.error("[fonts]", e.message);
  process.exit(1);
});
